### ISSUE TITLE
Readme.md 

### ISSUE THREAD

**Issue by marcos-caylent** [caylent/terraform-aws-cost-anomaly-detection#8]
### Readme.md 

There are a few typos: 

Line 1: Inmediately should be Immediately
Line 5: Recomended should be Recommended
Line 12: has double ** at the end
Line 25: Link does not seem to work for me 
Line 27: Link does not seem to work for me

### main.tf

Line 7: I suggest moving the data object to the `data.tf` file as you are already separating data resources from the main terraform code. This way you can keep the code clean and we have a clear separation between what's readonly and what's not. 

Line 31: Since the policy will only exist as the SNS topic policy and the creation conditions are the same, I suggest merging the policy and adding it as an additional attribute to the `cost_anomaly_topic` resource so that it can help with readability.

Line 95: I suspect there's a logic problem with adding dependencies here; First, the dependency between the topic and policy should be automatically resolved by terraform when you are creating the policy as standalone and referencing the topic (terraform should automatically infer the dependencies by resolving the interpolation statements) but secondly, you are adding a dependency to a conditional resource, what should be the expected behavior when adding an external sns? The `anomaly_subscription` resource will not be created as you'll have unresolved dependencies, is that acceptable?

### config.tf

By any chance, are we missing the provider configuration? Is this by design?

**Comment by manu-caylent** [comment]
check:
https://github.com/caylent/terraform-aws-cost-anomaly-detection/pull/9

all typos in readme.md fixed.
main.tf:line7 Done
main.tf:line31 generates a circular dependency unless sns_topic_policy_document uses * on the  resources section. This allows other monitors to use this topic but's considered a high-severity issue by tfsec.
main.tf:line95 fixed. Was forgotten after tests.
Config.tf: I will need more context. providers are configured in the examples module

**Comment by manu-caylent** [comment]
config.tf was a misunderstanding. All bugs were fixed.
